name: ci

on:
  push:
    branches:
    - "*"  # run forbranches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: carts
    steps:
    - uses: actions/checkout@v2


    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    #
    #
    # Build
    - name: Build jar files
      run: ./scripts/build.sh

    #
    #
    # Push to dockerhub
    - name: Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
    _ name: Build & push Docker image
      with:
       image: sujaysuj/javaappaction
       tags: latest
       registry: docker.io
       dockerfile: docker/carte/Dockerfile
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_PASS }}

      

